# Generated by Django 5.2.18 on 2026-10-07 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access the Shipyard dashboard"),
                    (
                        "manage_shipyard",
                        "Can edit blueprint prices, LP prices and facilities",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "structure_type_id",
                    models.PositiveIntegerField(
                        help_text="EVE type ID of the structure (Raitaru 35825, Azbel 35826, Sotiyo 35827, Astrahus 35832, Athanor 35835)"
                    ),
                ),
                ("structure_name", models.CharField(max_length=50)),
                (
                    "system_id",
                    models.PositiveIntegerField(
                        help_text="Solar system ID (Isikano 30001387)"
                    ),
                ),
                ("system_name", models.CharField(max_length=50)),
                (
                    "rig_type_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rig type IDs fitted",
                    ),
                ),
                (
                    "facility_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Facility tax set by the structure owner, in %",
                        max_digits=5,
                    ),
                ),
                (
                    "manufacturing_index",
                    models.FloatField(
                        default=0,
                        help_text="System manufacturing cost index (fraction), refreshed from ESI",
                    ),
                ),
                ("index_updated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "facilities",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="LpFaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "isk_per_lp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What a member pays per LP, in ISK",
                        max_digits=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "LP faction",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "station_id",
                    models.PositiveBigIntegerField(
                        help_text="Station or structure ID (Jita 4-4: 60003760)"
                    ),
                ),
                ("region_id", models.PositiveIntegerField(default=10000002)),
                ("is_npc_station", models.BooleanField(default=True)),
                (
                    "sales_tax_base",
                    models.DecimalField(
                        decimal_places=3,
                        default=7.5,
                        help_text="Base sales tax in % before Accounting skill (NPC stations: 7.5)",
                        max_digits=5,
                    ),
                ),
                (
                    "broker_fee_base",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.0,
                        help_text="Base broker fee in % (NPC station 3.0 before Broker Relations; player structure: owner-set)",
                        max_digits=5,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "type_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("volume", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RefreshRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("step", models.CharField(max_length=40)),
                ("ok", models.BooleanField(default=False)),
                ("items", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "type_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("group_id", models.PositiveIntegerField()),
                ("hull_size", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("faction_id", models.PositiveIntegerField(blank=True, null=True)),
                ("faction_name", models.CharField(blank=True, max_length=50)),
                ("meta_group_id", models.PositiveIntegerField(blank=True, null=True)),
                ("blueprint_type_id", models.PositiveIntegerField()),
                (
                    "volume",
                    models.FloatField(default=0, help_text="Packaged volume m³"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Shown on the dashboard"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShipConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bpc_price_isk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Blueprint cost per run (ISK), bought on the market",
                        max_digits=15,
                    ),
                ),
                (
                    "tag_cost_isk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tags or other extra inputs per run (ISK)",
                        max_digits=15,
                    ),
                ),
                (
                    "lp_cost",
                    models.PositiveIntegerField(
                        default=0, help_text="LP for one blueprint copy in the LP store"
                    ),
                ),
                (
                    "lp_isk_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="ISK part of the LP store offer",
                        max_digits=15,
                    ),
                ),
                (
                    "lp_runs",
                    models.PositiveIntegerField(
                        default=1, help_text="Runs on the copy from the LP store"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "lp_faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipyard.lpfaction",
                    ),
                ),
                (
                    "ship",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="shipyard.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipMarketStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.PositiveIntegerField(default=10000002)),
                ("avg_daily_volume", models.FloatField(default=0)),
                ("avg_price", models.FloatField(default=0)),
                ("days", models.PositiveSmallIntegerField(default=7)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ship",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_stats",
                        to="shipyard.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_lp_pricing",
                    models.BooleanField(
                        default=False,
                        help_text="Price blueprints from LP store offers where available",
                    ),
                ),
                ("skills_source", models.CharField(default="manual", max_length=10)),
                (
                    "skills_character_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("skills_character_name", models.CharField(blank=True, max_length=100)),
                ("skills_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("accounting", models.PositiveSmallIntegerField(default=0)),
                ("broker_relations", models.PositiveSmallIntegerField(default=0)),
                ("industry", models.PositiveSmallIntegerField(default=5)),
                ("advanced_industry", models.PositiveSmallIntegerField(default=5)),
                ("adv_small_ship", models.PositiveSmallIntegerField(default=0)),
                ("adv_medium_ship", models.PositiveSmallIntegerField(default=0)),
                ("adv_large_ship", models.PositiveSmallIntegerField(default=0)),
                ("adv_industrial_ship", models.PositiveSmallIntegerField(default=0)),
                (
                    "manual_sales_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Override sales tax % (from the in-game market window)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "manual_broker_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Override broker fee %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipyard.facility",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipyard.marketlocation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipyard_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user settings",
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.PositiveIntegerField()),
                ("sell_min", models.FloatField(null=True)),
                ("sell_percentile", models.FloatField(null=True)),
                (
                    "sell_volume",
                    models.FloatField(default=0, help_text="Units on sell orders"),
                ),
                ("sell_orders", models.PositiveIntegerField(default=0)),
                ("buy_max", models.FloatField(null=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipyard.marketlocation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["type_id"], name="shipyard_pr_type_id_bcad5e_idx"
                    )
                ],
                "unique_together": {("type_id", "location")},
            },
        ),
        migrations.CreateModel(
            name="BuildSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("me", models.PositiveSmallIntegerField(default=0)),
                (
                    "materials",
                    models.JSONField(default=list, help_text="[{type_id, quantity}]"),
                ),
                ("estimated_item_value", models.FloatField(default=0)),
                (
                    "job_cost",
                    models.FloatField(
                        default=0, help_text="Total job cost incl. SCC and facility tax"
                    ),
                ),
                ("system_cost_isk", models.FloatField(default=0)),
                ("scc_surcharge", models.FloatField(default=0)),
                ("facility_tax_isk", models.FloatField(default=0)),
                ("time_seconds", models.PositiveIntegerField(default=0)),
                ("materials_volume", models.FloatField(default=0)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builds",
                        to="shipyard.facility",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builds",
                        to="shipyard.ship",
                    ),
                ),
            ],
            options={
                "unique_together": {("ship", "facility", "me")},
            },
        ),
    ]
